### ISSUE TITLE
Brawlstats - Returning empty map

### ISSUE THREAD

**Issue by tnfAngel** [SpecteraLabs/npm-packages#7]
### Overview

The method getBrawlers returns an empty map.

### Re-production

Execute 
await client.getBrawlers();

### Minimal code for bug re-production

```typescript
await client.getBrawlers();
```

### Expected output

A map with all brawlers

### Actual output

BrawlersMap(0) [Map] {}
![image](https://user-images.githubusercontent.com/57068341/160899829-07f75c58-29cc-420d-ac12-1bbde5b275f9.png)

### Environment

Node v17.8.0 
brawlstats ^2.0.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have provided a sufficient amount of code to re-produce the bug or mine, if none.

**Comment by UndiedGamer** [comment]
Can you show how you initialized your client?

**Comment by tnfAngel** [comment]
I was using BRAWLSTARS_TOKEN, but reinstalled the package by deleting node_modules and the problem seems to be fixed. Thanks.

**Comment by tnfAngel** [comment]
The only thing that happens now is that it logs me undefined when calling the method, but it works correctly.
![image](https://user-images.githubusercontent.com/57068341/161388745-f649776e-2191-4779-8141-42eb66ea8a67.png)

**Comment by UndiedGamer** [comment]
you sure? i dont know where that undefined is coming from but the data is returned right?

**Comment by tnfAngel** [comment]
> you sure? i dont know where that undefined is coming from but the data is returned right?

yeah, the data returned after reinstall is right, only that undefined, in the code of the package i see an console.log in the Brawlers.js file, but isn't in the github code, maybe i need to update the package?

**Comment by UndiedGamer** [comment]
Yeah, the console log is from here
https://github.com/SpecteraLabs/npm-packages/blob/main/packages/brawlstats/CHANGELOG.md
Check the change log of 2.1.0 but you can't risk to install that version because typings were not exported so better update to 2.1.1

**Comment by tnfAngel** [comment]
> Yeah, the console log is from here
> https://github.com/SpecteraLabs/npm-packages/commit/62cfe7306f211f62aaebe42e41ac64b385568734
> Check the change log of 2.1.0 but you can't risk to install that version because typings were not exported on 2.1.0 so better update to 2.1.1

Okay, ty 👍

**Comment by UndiedGamer** [comment]
hey @tnfAngel we recently released v3, the changelog wasn't clear so just incase you wanted a migration guide:
https://brawlstatsjs.netlify.app/docs/Guide/migrating-from-v2

**Comment by tnfAngel** [comment]
> hey @tnfAngel we recently released v3, the changelog wasn't clear so just incase you wanted a migration guide:
> https://brawlstatsjs.netlify.app/docs/Guide/migrating-from-v2

Awesome! Thanks, i will take a look
